scss_files: 'src/scss/**/*.scss'

linters:

# airbnb default linter https://github.com/airbnb/css/blob/master/.scss-lint.yml
  BorderZero:
    enabled: true
    convention: none

  BemDepth:
    enabled: true

  DeclarationOrder:
    enabled: false

  LeadingZero:
    enabled: false

  PropertySortOrder:
    enabled: false

  QualifyingElement:
    enabled: false

  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM
    class_convention: ^(?!js-).*
    class_convention_explanation: should not be written in the form js-*

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false

  StringQuotes:
    enabled: true
    style: double_quotes

# BBC Search linter
  ElsePlacement:
    enabled: true
    style: same_line # or 'new_line'

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  EmptyRule:
    enabled: true

  HexLength:
    style: long

  HexNotation:
    enabled: true
    style: lowercase

  HexValidation:
    enabled: true

  Indentation:
    enabled: true
    character: space # or 'tab'
    width: 2

  MergeableSelector:
    enabled: true
    force_nesting: true

  NameFormat:
    enabled: false

  PlaceholderInExtend:
    enabled: false

  Shorthand:
    enabled: true

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true
    style: one_space # or 'no_space', or 'at_least_one_space', or 'aligned'

  SpaceBeforeBrace:
    enabled: true
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  TrailingSemicolon:
    enabled: true

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  ZeroUnit:
    enabled: true